### ISSUE TITLE
script to cleanup database

### ISSUE THREAD

**Issue by solutus** [bia-technologies/statsbit#6]
It could be convenient to have bash script for database cleanup like 
https://github.com/bia-technologies/statsbit#tips
```
-- Drop all chunks older than 3 months ago:
SELECT drop_chunks(interval '3 months');
```

In this case, it is possible to configure cleanup automatically by system administrators. 
I will be glad to know your opinion about it. 

Thanks for advance.

**Comment by darkleaf** [comment]
I think you should tweak [the retention policies](https://docs.timescale.com/api/latest/data-retention/add_retention_policy#optional-arguments).
Here are some examples for [a test server](https://github.com/bia-technologies/statsbit/blob/master/backend/resources/db/migration/test_server_2.x/R__timescale_settings.sql) and [a prod server](https://github.com/bia-technologies/statsbit/blob/master/backend/resources/db/migration/prod_server_2.x/R__timescale_settings.sql).

You can write your own migration and setup it with STATSBIT_BACKEND_MIGRATION_LOCATIONS as described in the readme file. Or you can simply execute the following commands:

```sql
select remove_retention_policy('metric-data', if_exists => true);
select add_retention_policy('metric-data', interval '1 month');

select remove_retention_policy('transaction-sample-data', if_exists => true);
select add_retention_policy('transaction-sample-data', interval '1 month');

select remove_retention_policy('analytic-event-data', if_exists => true);
select add_retention_policy('analytic-event-data', interval '1 month');

select remove_retention_policy('error-data', if_exists => true);
select add_retention_policy('error-data', interval '1 month');
```

**Comment by solutus** [comment]
@darkleaf,  thanks!
